runtime:
  container_commands:
  - apt-get update
  - apt-get install -y git
  python:
    version: '3.10'
    requirements:
    - pipeline-ai
    - easyocr
    - torch
    - torchvision
accelerators: ["nvidia_a100_5gb"]
pipeline_graph: ocr_v2:my_pl
pipeline_name: uriel/easyocr-r
description: null
readme: null
extras: {}
